---
- name: Create consul-exporter container
  become: true
  docker_container:
    name: "{{ consul_exporter_service_name }}"
    command: "{{ consul_exporter_args }}"
    detach: true
    image: "{{ consul_exporter_image }}"
    network_mode: host
    ports:
      - "9107:9107"
    state: present
  notify: restart consul-exporter

- name: Create consul-exporter service file
  become: true
  template:
    dest: "/etc/systemd/system/{{ consul_exporter_service_name }}.service"
    src: "templates/consul-exporter.service.j2"
    mode: 0664
  notify: restart consul-exporter


- name: Enable consul-exporter service
  become: true
  service:
    name: "{{ consul_exporter_service_name }}.service"
    state: started
    enabled: yes
